FROM java:8
COPY src /home/student/latihan/javahelloworld/src
WORKDIR /home/student/latihan/javahelloworld
RUN mkdir bin
RUN javac -d bin src/HelloWorld.java
ENTRYPOINT ["java", "-cp", "bin", "HelloWorld"]
